CollegeWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("course_application.urls")),
    path("auth/", include("authentication.urls")),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("forget_password/",views.ForgetPassword,name="forgetpassword"),
    path("reset_password/<token>/",views.ResetPassword,name="resetpassword"),
    path("changepassword/",views.changepassword,name="changepassword"),
    path("changingpwd/",views.changingpwd,name="changingpwd"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <title>{% block title %} Home {%endblock%}</title>
</head>
<style>
    body{
        /* margin-top: 20px; */
        text-align: center;
    }
    .apply{
        padding-top: 100px;
    }
    .msg{
        position: absolute;
        bottom:100px;
        width:100%;
        color: darkgreen;
    }
    .welcome{
        align-items: center;
        margin-top: 0.8rem;
        font-size:50px;
    }
    .nav{
        display: flex;
        padding: 5px 10px;
        background-color: rgba(234, 239, 236, 0.66);
        justify-content: flex-end;
    }

    .profile{
        width: fit-content;
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .link-primary{
        font-size: 1.5rem;
        
        
    }
    .login{
        padding-top: 100px;
        text-align: center;
    }
    
    @media (max-width: 1200px) {
        .welcome{
            font-size: 50px;

        }
        .link-primary{
            font-size: 40px;
        }
       
}
@media(max-width:768px){
    .welcome{
        font-size: 40px;
        /* text-align: left; */
    }
    .link-primary{
        font-size: 30px;
    }
    .logout{
        right:3%;
        top:25px;
    }
    
}
@media(max-width:480px){
    .welcome{
        font-size: 30px;
        /* text-align: left; */
    }
    .link-primary{
        font-size: 20px;
    }
    .logout{
        right:2%;
        top:20px;
    }
}
@media (max-width: 400px) and (max-height: 755px) {
    .welcome{
        font-size: 25px;
        text-align:left;
        }
    .link-primary{
        font-size: 20px;
    }
    .logout{
        right:2%;
        top:15px;
    }

}
</style>

<body>
    {%block body%}
    {% if user.is_authenticated %}
    <div class="nav">
        
        <div class="profile">
            <div><a href="{% url 'authentication:changepassword' %}" class="changepwd">Change Password</div>
                <div class="logout">
                    <a href="/auth/logout" class="btn btn-dark btn-block" role="button"></span>log out</a>
                </div>
            </div>
            
        </div>
        <h1 class="welcome">Welcome, {{ user.first_name }}</h1>
    {% if message %}
    <div class="apply">
    <a href="/honorsMinorsApplication" class="link-primary" >Modify Honors/Minors Application</a>
    </div>
    {% else %}
    <div class="apply">
    <a href="/honorsMinorsApplication" class="link-primary" >Apply for Honors/Minors</a>
    </div>
    {%endif%}
    
    {% if message != None %}
    <div class="msg">
    <h3 class="alert alert-success">{{ message }}</h3>
    </div>
    {%endif%}
    {% else %}
    <div class="login">
        <a class="btn btn-dark" href="/auth/login">Login </a>
        </div>
        {% endif %}

        {%endblock%}
        
</body>

</html>

templates/changepwd.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato&family=Ruwudu&display=swap');
      </style>
    <style>
@import url('https://fonts.googleapis.com/css2?family=Arimo&display=swap');
        * {
            overflow: hidden;
            font-family: 'Ruwudu', serif;
        }

        .form {
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 100vh;
            justify-content: center;
            margin-top: -14vh;
        }

        .form2 {
            display: flex;
            align-items: center;
            flex-direction: column;
        }

        .input {
            font-size: 1.5rem;
            color: orange;
			height: 40px;
            margin-top: 10px;
			align-items: center;
            margin-bottom: 5px;
        }

        .messages {
            padding: 10px;
            background-color: #f44336;
            color: white;
            font-size: 1rem;
            border-radius: 3px;
        }

        .submit {
            margin-top: 30px;
            background-color: orange;
            color: white;
            height: 35px;
            width: 96px;
            border: none;
            border-radius: 6px;
        }
        h1{
            font-family: 'Arimo', sans-serif;
        }
        .submit:hover {
            margin-top: 31px;
            font-weight: bolder;
        }
        @media (max-width : 560px) {
            *{
                font-size: 1rem;
            }
            .submit{
                height: 25px;
                width: 80px;
                font-size: 0.8rem;
            }
            input{
                width: 130px;
            }
        }
        @media (max-width :300px){
            input{
                width: 120px;
            }
        }
    </style>
	<title>Change Password</title>
</head>

<body>
    <div class="form">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }} " {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <h1>Change Password</h1>
        <form method="POST" class="form2" action="{% url 'authentication:changingpwd' %}">
            {% csrf_token %}
            <div class="input">
                <Label>Enter Old Password</Label>
                <input type="password" name="oldpassword" id="oldpwd">
            </div>
            <div class="input">
                <Label>Enter New password</Label>
                <input type="password" name="newpassword" id="newpwd">
            </div>
            <div class="input">
                <Label>Re-Enter New password</Label>
                <input type="password" name="newpassword2" id="newpwd2">
            </div>

			<div>
				<input type="checkbox" id="showpassword" onchange="myfunction()">
				<label for="showpassword">Show Password</label>
			</div>
            <div>
                <input type="submit" class="submit" value="SUBMIT">
            </div>

        </form>
    </div>

	<script>
        function myfunction() {
            let oldpwd = document.getElementById('oldpwd');
            let newpwd = document.getElementById('newpwd');
            let newpwd2 = document.getElementById('newpwd2');

            let showPasswordCheckbox = document.getElementById("showpassword");
            oldpwd.type = showPasswordCheckbox.checked ? "text" : "password";
            newpwd.type = showPasswordCheckbox.checked ? "text" : "password";
            newpwd2.type = showPasswordCheckbox.checked ? "text" : "password";
        }
    </script>
</body>

</html>

templates/forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Validation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <style>

*{
    align-items: center;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body{
    font-family: 'Poppins', sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: rgb(246, 255, 255);

}


.continer{
    justify-content: center;
    background-color: rgb(253, 253, 253);
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    border-radius: 10px;
    width: 400px;

}

.continer h1{

    text-align: center;
    margin: 50px;
}

.form{

    padding: 30px 40px;
}

.form-control{
    margin-bottom: 10px;
    padding-bottom: 5px;
    position: relative;
}

.form-control label{
    display: block;
    margin-bottom: 5px;

}

.form-control input{
    width: 100%;
    padding: 5px 15px;
    font-size: 16px;
    border: 1px solid rgb(158, 158, 158);
}

.form-control input:focus{
    outline: none;
    border: 1px solid rgb(110, 110, 110)
}

.form button.btn{
    width: 100%;
    padding: 10px 15px;
    border: none;
    cursor: pointer;
    background-color: rgb(238, 155, 0);
    color: #fff;   
}
.log{
    text-align: center;
}
</style>
   
</head>
<body>
<div class="continer">
    <form class="form" method="post" id="form">
        {% csrf_token %}
        <h4>Forget Password</h4>

        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="password">Username</label>
            <input type="text" name="username"  class="form-control" required>   
        </div>

        <button class="btn" type="submit">Submit</button>
        <div class="log">
        <p>or <a href="{% url 'authentication:login' %}">Log in</a></p>
            </div>
    </form>
</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <title>Login</title>
    <script>
        function myfunction() {
            var passwordInput = document.getElementById("password");
            var showPasswordCheckbox = document.getElementById("showpassword");
            passwordInput.type = showPasswordCheckbox.checked ? "text" : "password";
        }
    </script>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        text-align: center;
    }

    .background-image {
        position: absolute;
        background-image: url("https://www.yuvamind.com/colleges/images/college/jntu-gv-college-of-engineering-campus.png");
        background-repeat: no-repeat;
        background-size: cover;
        filter: blur(3px);
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }

    .content {
        align-items: center;
    }

    .container {
        display: flex;
        justify-content: center;
        height: 100vh;
    }

    .form-container {
        width: 70%;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .loginform {
        flex-basis: 50%;
        background: white;
        font-family: cursive;
        border-radius: 5px;
        padding: 25px;
        border-style: outset;
    }

    .loginform h1 {
        text-align: center;
        font-size: 2.5em;
        margin-bottom: 20px;
        color: black;
    }

    .tbox {
        border-radius: 3px;
        background: transparent;
        outline: none;
        border: 1px solid black;
        width: 100%;
        height: 35px;
        margin: 30px 0;
    }

    .tbox input {
        background: transparent;
        width: 90%;
        outline: none;
        border: 0;
        padding-left: 5px;
        color: black;
    }

    ::placeholder {
        color: black;
        font-size: small;
    }

    .tbox i {
        color: black;
        font-size: 15px;
        padding: 7px;
    }

    .btn {
        padding: 15px 30px;
        border: none;
        border-radius: 6px;
        background-color: black;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        transition: transform 0.3s ease;
    }

    .btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 10px rgba(0, 0, 0, 0.3);
        color:white;
    }

    .btn:active {
        transform: translateY(3px);
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
    }

    @media only screen and(max-width:800px) and (min-width:300px) {
        .login {
            flex-direction: column;
            margin: 0 15px 1;
        }
    }
</style>

<body>

    <div class="container">

        <div class="background-image"> </div>
        <div class="form-container">
            <div class="loginform">
                <div class="content">
                    <img src="https://dhondi.ai/logos/jntugv.png" alt="JNTU-GV" float="center" width="250" height="250">
                </div>
                <h1>Login</h1>
                {% if messages %}
                {% for message in messages %}
                {% if forloop.last %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}
                <form method="post" action="{% url 'authentication:login' %}">
                    {% csrf_token %}
                    <div class="tbox">
                        <i class="fa fa-user"></i><input type="text" name="username" id="username"
                            placeholder="Username" required>
                    </div>
                    <div class="tbox">
                        <i class="fa fa-lock"></i><input type="password" id="password" name="password"
                            placeholder="Password" required>
                    </div>
                    <div>
                        <input type="checkbox" id="showpassword" onchange="myfunction()">
                        <label for="showpassword">Show Password</label>
                    </div>

                    <button class="btn">Login</button>
                    <p class="psw"><a href="{% url 'authentication:forgetpassword' %}">Forgot password?</a></p>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Validation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script>
        function myfunction() {
            var passwordInput = document.getElementById("password");
            var repasswordInput = document.getElementById("repassword");
            var showPasswordCheckbox = document.getElementById("showpassword");
            passwordInput.type = showPasswordCheckbox.checked ? "text" : "password";
            repasswordInput.type = showPasswordCheckbox.checked ? "text" : "repassword";
        }
    </script>
<style>
*{

    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body{
    font-family: 'Poppins', sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: rgb(246, 255, 255);

}


.continer{

    background-color: rgb(253, 253, 253);
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    border-radius: 10px;
    width: 400px;

}

.continer h1{

    text-align: center;
    margin: 50px;
}

.form{
    padding: 30px 40px;
}

.form-control{
    margin-bottom: 10px;
    padding-bottom: 5px;
    position: relative;
}

.form-control label{
    display: block;
    margin-bottom: 5px;

}

.form-control input{
    width: 100%;
    padding: 5px 15px;
    font-size: 16px;
    border: 1px solid rgb(158, 158, 158);
}

.form-control input:focus{
    outline: none;
    border: 1px solid rgb(110, 110, 110)
}

.form button.btn{
    width: 100%;
    padding: 10px 15px;
    border: none;
    cursor: pointer;
    background-color: rgb(238, 155, 0);
    color: #fff;   
}
.psw{
    text-align: center;
}

</style>
<div class="continer">
    <form method="post" class="form" id="form">
        {% csrf_token %}
        <h4>Change Password</h4>
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

     
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="new_password"  class="form-control" id="password" required>
           
        </div>



        <div class="form-group">
            <label for="password">Re confirm password</label>
            <input type="password" name="reconfirm_password"   class="form-control" id="repassword" required>
           
        </div>


        <input type="hidden" name="user_id" value="{{user_id}}">
        
        <div class="psw">
            <input type="checkbox" id="showpassword" onchange="myfunction()">
            <label for="showpassword">Show Password</label>
        </div>
       
        <button class="btn" type="submit">Submit</button>
        

    </form>
</div>

templates/submitted.html
{% extends "base.html" %}

{% block title %}Application Submission{% endblock %}

{% block body %}
{% if messages %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% elif message.tags == 'success' %}
<div class="alert alert-success" role="alert">
    <h3>{{ message }}</h3>
</div>
<a href="/" style="font-size: 30px;margin-top: 20px;">Go to Home</a>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}